BoxLayoutExample:

<BoxLayoutExample>:
    orientation: "vertical"
    Button:
        text: "A"
        size: "40dp", "20dp"
        size_hint: None, None
    Button:
        text: "B"
    Label:
        text: "C"



<MainWidget>:
    Button:
        text: "Hello"
        size: "40dp", "20dp"
        pos: "10dp", "20dp"
        color: 0,0,1,1
    Label:
        text: "Hello2"
        size: "40dp", "20dp"
        pos: "150dp", "200dp"
        color: 1,0,0,1